### ISSUE TITLE
mobile safariで見たとき公開範囲のアイコンが表示されない

### ISSUE THREAD

**Issue by kmtr** [digu/digu#9]

**Comment by dongri** [comment]
![image uploaded from ios](https://cloud.githubusercontent.com/assets/878993/25231672/aab71886-2613-11e7-9c47-86ac2d3aa52c.jpg)

地球アイコンと人のアイコン出てますが、別のことですか？

**Comment by kmtr** [comment]
それのことです。私の環境では表示されないですね。

**Comment by dongri** [comment]
@kmtr 今日一回見せてください

**Comment by kmtr** [comment]
こんな感じです。
![bug_report](https://cloud.githubusercontent.com/assets/1112332/25362853/6a858e74-2991-11e7-9695-46cc24930123.png)

**Comment by kmtr** [comment]
原因がわかりました。Safariの設定でコンテンツブロッカーを有効にしているのですが、
それによって外部CSS(fonts.googleapis.com)の読み込みがブロックされているために発生しているようです。
なので、バグというわけでは無さそうです。

対応するしないについてはお任せします。

**Comment by dongri** [comment]
なるほど、ありますございます。対応します。google fontsがでかくなければ

**Comment by dongri** [comment]
簡単なやつなのでやっちゃいました。もう一回確認お願いしますmm

**Comment by kmtr** [comment]
確認できました。ありがとうございます。

ただ、使っているブロッカーには、3rd party CSS/scriptのブロックの他に、
さらにウェブフォント機能そのもののブロック機能があり、これを有効だと自分のサイトのウェブフォントも使えなくなるという仕組みになっていました。

**Comment by dongri** [comment]
なるほど、厳しい。。。
